In [ ]:
from Phase_1.DataLoader import DataLoader
from Phase_1.DataValidator import DataValidator
from Phase_1.DataPreprocessor import DataPreprocessor
from Phase_1.OutlierHandler import OutlierHandler
file_path = "train.csv"
# file_path = "heart.csv"
# file_path_2 = "Data.xlsx"

data = DataLoader(file_path)
data.load()
data = data.get_data()
data

CSV file loaded successfully

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# val_data = DataValidator(data)
# val_data.check_nulls()

Null values found in 3 column(s).

{'Age': 177, 'Cabin': 687, 'Embarked': 2}

In [8]:
print(val_data.check_duplicates())
print(val_data.check_types())

No duplicate rows found.
0
Data types retrieved successfully.
{'PassengerId': 'int64', 'Survived': 'int64', 'Pclass': 'int64', 'Name': 'object', 'Sex': 'object', 'Age': 'float64', 'SibSp': 'int64', 'Parch': 'int64', 'Ticket': 'object', 'Fare': 'float64', 'Cabin': 'object', 'Embarked': 'object'}

In [9]:
val_data.report_issues()

Null values found in 3 column(s).
Data types retrieved successfully.
No duplicate rows found.

{'missing_values': {'Age': 177, 'Cabin': 687, 'Embarked': 2},
 'data_types': {'PassengerId': 'int64',
  'Survived': 'int64',
  'Pclass': 'int64',
  'Name': 'object',
  'Sex': 'object',
  'Age': 'float64',
  'SibSp': 'int64',
  'Parch': 'int64',
  'Ticket': 'object',
  'Fare': 'float64',
  'Cabin': 'object',
  'Embarked': 'object'},
 'duplicates': 0}

In [13]:
from Phase_1.DataPreprocessor import DataPreprocessor
preprocess = DataPreprocessor(data)
preprocess.handle_nulls()

Filled nulls in 'Age' with Median: 28.0.
Dropping column 'Cabin' due to high null ratio (77.10%).
Dropping rows with nulls in 'Embarked' (low ratio: 0.22%).

d:\git\depi\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:50: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [28]:
print("Before conversion:")
print(data[['Name', 'Sex', 'Age', 'Fare', 'Survived', 'Pclass']].dtypes)

Before conversion:
Name         object
Sex          object
Age         float64
Fare        float64
Survived      int64
Pclass        int64
dtype: object

In [ ]:
# schema-based conversion with more columns
test_schema = {
    'Survived': 'bool',
    'Pclass': 'category',
    'Fare': 'float32' 
}


preprocess.convert_types(schema=test_schema)

# dtypes after conversion
print("Data types after manual schema conversion:")
print(preprocess.get_clean_data()[['Survived', 'Pclass', 'Fare']].dtypes)

Data types after manual schema conversion:
Survived        bool
Pclass      category
Fare         float32
dtype: object

In [ ]:
# before conversion
print("Memory before:", data.memory_usage(deep=True).sum(), "bytes")


preprocess.convert_types(schema)

# after conversion
print("Memory after:", preprocess.get_clean_data().memory_usage(deep=True).sum(), "bytes")

Memory before: 292464 bytes
Memory after: 266178 bytes

In [15]:
preprocess.remove_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [30]:
preprocess.get_clean_data()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250000,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.283302,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925000,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.099998,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050000,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000000,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000000,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.450001,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000000,C
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750000,Q

In [1]:
import pandas as pd
from  Phase_1.ReportGenerator import ReportGenerator

df = pd.read_csv("train.csv")

report = ReportGenerator(df)

# Basic report
report.generate_report(mode="basic")

# Detailed report
report.generate_report(mode="detailed")

template exists: True

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:00<00:00, 15.99it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

'Detailed report generated'

In [3]:
import os
template_path = os.path.join("template.html")
print("template exists:", os.path.exists(template_path))

template exists: False

In [1]:
import pandas as pd
from  Phase_1.ReportGenerator import ReportGenerator

# load data
df = pd.read_csv("train.csv")

# create object
report = ReportGenerator(df)

# generate report
output_file = report.manual_report()

print("Report generated at:", output_file)

template exists: True
BASE_DIR: d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1
PROJECT_ROOT: d:\DEPI\Projects\Graduation-Project-DEPI-Round_4
OUTPUT: d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\final_report.html
Report generated at: d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\final_report.html