In [1]:
# Imports 
from Phase_1.DataLoader import DataLoader
from Phase_1.DataValidator import DataValidator
from Phase_1.DataPreprocessor import DataPreprocessor
from Phase_1.OutlierHandler import OutlierHandler
from Phase_1.ReportGenerator import ReportGenerator
from Phase_1.EDAPipeline import EDAPipeline

In [2]:
# check DataLoader
file_path = "train.csv"

data = DataLoader(file_path)
data.load()
data = data.get_data()
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
# check DataValidator
validator = DataValidator(data)
validator.check_nulls()
validator.check_types()
validator.check_duplicates()
validator.report_issues()

Null values found in 3 column(s).
Data types retrieved successfully.
No duplicate rows found.
Null values found in 3 column(s).
Data types retrieved successfully.
No duplicate rows found.

{'missing_values': {'Age': 177, 'Cabin': 687, 'Embarked': 2},
 'data_types': {'PassengerId': 'int64',
  'Survived': 'int64',
  'Pclass': 'int64',
  'Name': 'object',
  'Sex': 'object',
  'Age': 'float64',
  'SibSp': 'int64',
  'Parch': 'int64',
  'Ticket': 'object',
  'Fare': 'float64',
  'Cabin': 'object',
  'Embarked': 'object'},
 'duplicates': 0}

In [6]:
# check Datapreprocessor
preprocessor = DataPreprocessor(data)
preprocessor.handle_nulls()
preprocessor.convert_types()
preprocessor.remove_duplicates()
preprocessor.handle_outliers()
preprocessor.get_clean_data()

Filled nulls in 'Age' with Median: 28.0.
Dropping column 'Cabin' due to high null ratio (77.10%).
Dropping rows with nulls in 'Embarked' (low ratio: 0.22%).
Advanced type conversion and memory optimization completed.
  'PassengerId' capped between [-442.0, 1334.0]
  'Survived' capped between [-1.5, 2.5]
  'Pclass' capped between [0.5, 4.5]
  'Age' capped between [2.5, 54.5]
  'SibSp' capped between [-1.5, 2.5]
  'Parch' capped between [0.0, 0.0]
  'Fare' capped between [-26.76, 65.66]

Data capped successfully using IQR method.
Outliers handled automatically via OutlierHandler.

d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.250000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,65.656300,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.925000,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.099998,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.050000,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0.0,0,211536,13.000000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0,112053,30.000000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1.0,0,W./C. 6607,23.450001,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0,111369,30.000000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0.0,0,370376,7.750000,Q

In [7]:
# check OutlierHandler
outlier_handler = OutlierHandler(data)
outlier_handler.detect_iqr()
outlier_handler.detect_zscore()
outlier_handler.remove_outliers()
outlier_handler.cap_outliers()

IQR outlier detection completed.
Z-score outlier detection completed.
Outliers removed successfully using IQR method.
  'PassengerId' capped between [-444.0, 1336.0]
  'Survived' capped between [-1.5, 2.5]
  'Pclass' capped between [0.5, 4.5]
  'Age' capped between [-6.69, 64.81]
  'SibSp' capped between [-1.5, 2.5]
  'Parch' capped between [0.0, 0.0]
  'Fare' capped between [-26.72, 65.63]

Data capped successfully using IQR method.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,65.6344,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0.0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0.0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,0,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0.0,0,370376,7.7500,NaN,Q

In [8]:
# check ReportGenerator
report_generator = ReportGenerator(data)
report_generator.summary_stats()
report_generator.correlation_matrix()
report_generator.missing_values()
report_generator.manual_report()
report_generator.auto_report()
report_generator.generate_report()

template exists: True

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:00<00:00, 21.03it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

template exists: True

'HTML report generated'

In [10]:
# Check EDAPipeline
pipeline = EDAPipeline("train.csv")
pipeline.run_pipeline()

CSV file loaded successfully

==================================================
  1 — VALIDATING DATA
==================================================
Null values found in 3 column(s).
Data types retrieved successfully.
No duplicate rows found.
  • Nulls found    : {'Age': 177, 'Cabin': 687, 'Embarked': 2}
  • Duplicates     : 0
  • Column dtypes  : {'PassengerId': 'int64', 'Survived': 'int64', 'Pclass': 'int64', 'Name': 'object', 'Sex': 'object', 'Age': 'float64', 'SibSp': 'int64', 'Parch': 'int64', 'Ticket': 'object', 'Fare': 'float64', 'Cabin': 'object', 'Embarked': 'object'}

==================================================
  2 — PREPROCESSING DATA
==================================================
Filled nulls in 'Age' with Median: 28.0.
Dropping column 'Cabin' due to high null ratio (77.10%).
Dropping rows with nulls in 'Embarked' (low ratio: 0.22%).
Advanced type conversion and memory optimization completed.

==================================================
  3 — HANDLING OUTLIERS
==================================================

  [IQR Detection]
IQR outlier detection completed.
    • 'Age': 65 outlier(s)
    • 'SibSp': 46 outlier(s)
    • 'Parch': 213 outlier(s)
    • 'Fare': 114 outlier(s)

  [Z-Score Detection]
Z-score outlier detection completed.
    • 'Age': 7 outlier(s)
    • 'SibSp': 30 outlier(s)
    • 'Parch': 15 outlier(s)
    • 'Fare': 20 outlier(s)
  'PassengerId' capped between [-442.0, 1334.0]
  'Survived' capped between [-1.5, 2.5]
  'Pclass' capped between [0.5, 4.5]
  'Age' capped between [2.5, 54.5]
  'SibSp' capped between [-1.5, 2.5]
  'Parch' capped between [0.0, 0.0]
  'Fare' capped between [-26.76, 65.66]

Data capped successfully using IQR method.

==================================================
  4 — GENERATING REPORT
==================================================
template exists: True

==================================================
  PIPELINE COMPLETE ✓
==================================================
  Final dataset shape: (889, 11)

d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\DEPI\Projects\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])