In [1]:
# Imports 
from Phase_1.DataLoader import DataLoader
from Phase_1.DataValidator import DataValidator
from Phase_1.DataPreprocessor import DataPreprocessor
from Phase_1.OutlierHandler import OutlierHandler
from Phase_1.ReportGenerator import ReportGenerator
from Phase_1.EDAPipeline import EDAPipeline

In [2]:
# check DataLoader
file_path = "heart.csv"

data = DataLoader(file_path)
data.load()
data = data.get_data()
data

CSV file loaded successfully

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40.0,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49.0,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37.0,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48.0,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54.0,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,M,TA,110,264.0,0,Normal,132,N,1.2,Flat,1
914,68.0,M,ASY,144,193.0,1,Normal,141,N,3.4,Flat,1
915,57.0,M,ASY,130,131.0,0,Normal,115,Y,1.2,Flat,1
916,57.0,F,ATA,130,236.0,0,LVH,174,N,0.0,Flat,1
917,38.0,M,NAP,138,175.0,0,Normal,173,N,0.0,Up,0

In [3]:
# check DataValidator
validator = DataValidator(data)
validator.check_nulls()
validator.check_types()
validator.check_duplicates()
validator.report_issues()

Null values found in 2 column(s).
Data types retrieved successfully.
No duplicate rows found.
Null values found in 2 column(s).
Data types retrieved successfully.
No duplicate rows found.

{'missing_values': {'Age': 49, 'Cholesterol': 79},
 'data_types': {'Age': 'float64',
  'Sex': 'object',
  'ChestPainType': 'object',
  'RestingBP': 'int64',
  'Cholesterol': 'float64',
  'FastingBS': 'int64',
  'RestingECG': 'object',
  'MaxHR': 'int64',
  'ExerciseAngina': 'object',
  'Oldpeak': 'float64',
  'ST_Slope': 'object',
  'HeartDisease': 'int64'},
 'duplicates': 0}

In [4]:
# check Datapreprocessor
preprocessor = DataPreprocessor(data)
preprocessor.handle_nulls()
preprocessor.convert_types()
preprocessor.remove_duplicates()
preprocessor.handle_outliers()
preprocessor.get_clean_data()

Filled nulls in 'Age' with Median: 54.0.
Filled nulls in 'Cholesterol' with Median: 223.0.
Advanced type conversion and memory optimization completed.
  'Age' capped between [30.0, 78.0]
  'RestingBP' capped between [90.0, 170.0]
  'Cholesterol' capped between [65.5, 381.5]
  'FastingBS' capped between [0.0, 0.0]
  'MaxHR' capped between [66.0, 210.0]
  'Oldpeak' capped between [-2.25, 3.75]
  'HeartDisease' capped between [-1.5, 2.5]

Data capped successfully using IQR method.
Outliers handled automatically via OutlierHandler.

d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40.0,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49.0,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37.0,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48.0,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54.0,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,M,TA,110,264.0,0,Normal,132,N,1.2,Flat,1
914,68.0,M,ASY,144,193.0,0,Normal,141,N,3.4,Flat,1
915,57.0,M,ASY,130,131.0,0,Normal,115,Y,1.2,Flat,1
916,57.0,F,ATA,130,236.0,0,LVH,174,N,0.0,Flat,1
917,38.0,M,NAP,138,175.0,0,Normal,173,N,0.0,Up,0

In [5]:
# check OutlierHandler
outlier_handler = OutlierHandler(data)
outlier_handler.detect_iqr()
outlier_handler.detect_zscore()
outlier_handler.remove_outliers()
outlier_handler.cap_outliers()

IQR outlier detection completed.
Z-score outlier detection completed.
Outliers removed successfully using IQR method.
  'Age' capped between [27.5, 79.5]
  'RestingBP' capped between [90.0, 170.0]
  'Cholesterol' capped between [40.5, 404.5]
  'FastingBS' capped between [0.0, 0.0]
  'MaxHR' capped between [66.0, 210.0]
  'Oldpeak' capped between [-2.25, 3.75]
  'HeartDisease' capped between [-1.5, 2.5]

Data capped successfully using IQR method.

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40.0,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49.0,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37.0,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48.0,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54.0,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,M,TA,110,264.0,0,Normal,132,N,1.2,Flat,1
914,68.0,M,ASY,144,193.0,0,Normal,141,N,3.4,Flat,1
915,57.0,M,ASY,130,131.0,0,Normal,115,Y,1.2,Flat,1
916,57.0,F,ATA,130,236.0,0,LVH,174,N,0.0,Flat,1
917,38.0,M,NAP,138,175.0,0,Normal,173,N,0.0,Up,0

In [6]:
# check ReportGenerator
report_generator = ReportGenerator(data)
report_generator.summary_stats()
report_generator.correlation_matrix()
report_generator.missing_values()
report_generator.manual_report()
report_generator.auto_report()
report_generator.generate_report()

template exists: True

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\Amit_env\Lib\site-packages\ydata_profiling\model\correlations.py:66: UserWarning: There was an attempt to calculate the auto correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"auto": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: 'ATA'')
  warnings.warn(
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\Amit_env\Lib\site-packages\seaborn\matrix.py:260: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
  annotation = ("{:" + self.fmt + "}").format(val)
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\Amit_env\Lib\site-packages\ydata_profiling\model\missing.py:78: UserWarning: There was an attempt to generate the Heatmap missing values diagrams, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(missing_diagrams={"Heatmap": False}`)
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: '--'')
  warnings.warn(

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

template exists: True

'HTML report generated'

In [8]:
# Check EDAPipeline
pipeline = EDAPipeline("heart.csv")
pipeline.run_pipeline()

CSV file loaded successfully

==================================================
  1 — VALIDATING DATA
==================================================
Null values found in 2 column(s).
Data types retrieved successfully.
No duplicate rows found.
  • Nulls found    : {'Age': 49, 'Cholesterol': 79}
  • Duplicates     : 0
  • Column dtypes  : {'Age': 'float64', 'Sex': 'object', 'ChestPainType': 'object', 'RestingBP': 'int64', 'Cholesterol': 'float64', 'FastingBS': 'int64', 'RestingECG': 'object', 'MaxHR': 'int64', 'ExerciseAngina': 'object', 'Oldpeak': 'float64', 'ST_Slope': 'object', 'HeartDisease': 'int64'}

==================================================
  2 — PREPROCESSING DATA
==================================================
Filled nulls in 'Age' with Median: 54.0.
Filled nulls in 'Cholesterol' with Median: 223.0.
Advanced type conversion and memory optimization completed.

==================================================
  3 — HANDLING OUTLIERS
==================================================

  [IQR Detection]
IQR outlier detection completed.
    • 'Age': 9 outlier(s)
    • 'RestingBP': 28 outlier(s)
    • 'Cholesterol': 168 outlier(s)
    • 'FastingBS': 214 outlier(s)
    • 'MaxHR': 2 outlier(s)
    • 'Oldpeak': 16 outlier(s)

  [Z-Score Detection]
Z-score outlier detection completed.
    • 'Age': 5 outlier(s)
    • 'RestingBP': 8 outlier(s)
    • 'Cholesterol': 4 outlier(s)
    • 'MaxHR': 1 outlier(s)
    • 'Oldpeak': 7 outlier(s)
  'Age' capped between [30.0, 78.0]
  'RestingBP' capped between [90.0, 170.0]
  'Cholesterol' capped between [65.5, 381.5]
  'FastingBS' capped between [0.0, 0.0]
  'MaxHR' capped between [66.0, 210.0]
  'Oldpeak' capped between [-2.25, 3.75]
  'HeartDisease' capped between [-1.5, 2.5]

Data capped successfully using IQR method.

==================================================
  4 — GENERATING REPORT
==================================================
template exists: True

==================================================
  PIPELINE COMPLETE ✓
==================================================
  Final dataset shape: (918, 12)

d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[col].fillna(median_val, inplace=True)
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])
d:\Gemy Study\DEPI\Machine learning DEPI round_4\TEC\Amit-1\src\ML\Graduation-Project-DEPI-Round_4\Phase_1\DataPreprocessor.py:105: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  self.data[col] = pd.to_datetime(self.data[col])